apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  namespace: {{ .Values.mysqlNamespace }}
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{- if $v }}
  {{ $.Values.prefix }}{{ $k | replace "-" "_"  | upper }}: {{ $v | quote }}
  {{- end }}
  {{- end }}